HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - Keystone'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  KeystoneDbHost:
    Default: '192.168.122.1'
    Description: Database Host for Keystone
    Type: String
  KeystoneDbUser:
    Default: keystone
    Description: Database User for Keystone
    Type: String
  KeystoneDbPassword:
    Default: keystone
    Description: Database Password for Keystone
    Type: String
  KeystoneDatabase:
    Default: keystone
    Description: Database for Keystone
    Type: String
  KeystoneImage:
    Type: String
Resources:
  KeystoneLaunch:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        {Ref: KeystoneImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      AWS::CloudFormation::Init:
        config:
            files:
                /tmp/init-done:
                    content: ''
                    owner: root
                    group: root
                    mode: '000644'
      TripleO::ImageBuilder::Elements: [ keystone ]
      OpenStack::Keystone::Database:
        Host:
          Ref: KeystoneDbHost
        User:
          Ref: KeystoneDbUser
        Database:
          Ref: KeystoneDatabase
        Password:
          Ref: KeystoneDbPassword
  Keystone:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchConfigurationName: KeystoneLaunch
      AvailabilityZones: [ 1 ]
      MinSize: '1'
      MaxSize: '3'
