HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - All OpenStack Components'
Parameters:
  KeyName: {Description: Name of an existing EC2 KeyPair
      to enable SSH access to the instances, Type: String, Default: default}
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  MySQLImage:
    Type: String
Resources:
  AllDB:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
            files:
                /tmp/init-done:
                    content: ''
                    owner: root
                    group: root
                    mode: '000644'
      TripleO::ImageBuilder::Elements: [ mysql ]
    Properties:
      ImageId:
        {Ref: MySQLImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
